# Generated by Django 3.2.25 on 2024-07-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20240623_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_thumbnail',
            field=models.ImageField(default='blog/default.jpg', upload_to='blog/'),
        ),
    ]
