# Generated by Django 3.2.25 on 2024-07-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_image_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_thumbnail',
            field=models.ImageField(default='blog/default.jpg', upload_to='blog/thumbnails/'),
        ),
    ]
