# Generated by Django 3.2.25 on 2024-07-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_image_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_thumbnail',
            field=models.ImageField(upload_to='blog/thumbnails/'),
        ),
    ]
